materias = {
    "Língua Portuguesa": "Aprofundamento no estudo da língua, gramática e produção textual.",
    "Literatura": "Análise e interpretação de obras literárias.",
    "Matemática": "Estudo avançado de álgebra, geometria, trigonometria e estatística.",
    "Física": "Aprofundamento em conceitos de física, incluindo mecânica, termodinâmica e eletricidade.",
    "Química": "Estudo avançado da química, incluindo reações químicas, estequiometria e química orgânica.",
    "Biologia": "Estudo avançado sobre organismos, genética, evolução e ecologia.",
    "História": "Análise crítica de eventos históricos, suas causas e consequências.",
    "Geografia": "Estudo das dinâmicas espaciais, sociais e econômicas do mundo.",
    "Inglês": "Aprofundamento no aprendizado da língua inglesa, incluindo conversação e escrita.",
    "Educação Física": "Prática e desenvolvimento de habilidades em diversos esportes e atividades físicas.",
    "Filosofia": "Estudo de questões éticas, existenciais e do conhecimento humano.",
    "Sociologia": "Análise de estruturas sociais, cultura e comportamento humano.",
    "Redação": "Aprimoramento das habilidades de escrita, argumentação e estruturação de textos.",
    "Artes": "Exploração de diversas formas de expressão artística, como pintura, música e teatro.",
}

'''nomes_alunos = [
    "José Lucas", 
    "Maria Silva", 
    "Carlos Souza", 
    "Ana Oliveira", 
    "Lucas Pereira",
    "Mariana Costa", 
    "Fernando Lima", 
    "Tatiane Rocha", 
    "Roberto Almeida", 
    "Juliana Santos",
    "Gabriel Mendes", 
    "Luciana Gomes", 
    "Rafael Ferreira", 
    "Larissa Martins", 
    "Thiago Ribeiro",
    "Camila Nascimento", 
    "Eduardo Lima", 
    "Aline Dias", 
    "Marcelo Pires", "Juliana Alves",
    "Bruno Santos", "Fernanda Vieira", "Vinícius Rocha", "Isabella Castro", "João Pedro",
    "Carolina Martins", "Danilo Santos", "Clara Oliveira", "Felipe Mendes", "Priscila Ramos",
    "Tiago Moreira", "Letícia Almeida", "Jéssica Costa", "Mateus Ferreira", "Renata Lopes",
    "Gustavo Lima", "Tatiane Silva", "André Souza", "Paula Rocha", "Simone Almeida",
    "Cecília Ferreira", "Lucas Alves", "Victor Hugo", "Marina Costa", "Elias Silva",
    "Patrícia Gomes", "Robson Santos", "Amanda Ferreira", "Sérgio Almeida", "Denise Martins",
    "Renan Nascimento", "Brenda Lima", "Otávio Oliveira", "Rogério Souza", "Marília Castro",
    "Julio Lima", "Mariane Gomes", "Adriana Pires", "Marcelo Silva", "Claudia Almeida",
    "Pedro Henrique", "Sofia Martins", "Diego Santos", "Giselle Ribeiro", "Simone Alves",
    "Eduardo Lopes", "Jessica Ferreira", "Rafael Gomes", "Lucas Costa", "Mônica Santos",
    "Cynthia Oliveira", "Gustavo Almeida", "Natália Ferreira", "Luiz Carlos", "Tânia Ribeiro",
    "Fábio Lima", "Luiza Nascimento", "Carlos Alberto", "Débora Alves", "Claudio Ferreira",
    "Rosana Costa", "Flávio Gomes", "Sonia Martins", "Júlio César", "Fernanda Pires",
    "Matheus Silva", "Tatiane Ferreira", "Aline Oliveira", "Ricardo Mendes", "Lucas Andrade",
    "Tatiane Almeida", "Felipe Lima", "Bruno Alves", "Eduarda Gomes", "Daniel Ferreira",
    "Rafael Alves", "Fernando Costa", "Ruth Oliveira", "Lucas Pereira", "Samantha Rocha",
    "Guilherme Martins", "Larissa Andrade", "Vitor Hugo", "Yasmin Costa", "Thiago Pires",
    "Natália Ramos", "Rafael Costa", "Igor Almeida", "Sabrina Gomes", "Luiz Fernando",
    "Adriana Costa", "Felipe Souza", "Gabriela Lima", "Eliane Ferreira", "Samuel Martins",
    "Juliana Oliveira", "Vinícius Lima", "Lúcia Almeida", "Filipe Santos", "Amanda Silva",
    "Gabriel Ferreira", "Camila Oliveira", "Daniela Rocha", "Rafael Nascimento", "Tais Lima",
    "Fernando Ribeiro", "Leonardo Gomes", "Patrícia Santos", "Robson Ferreira", "Heloísa Lima",
    "Marcos Andrade", "Cinthia Almeida", "Érica Rocha", "Mariana Nascimento", "Alexandre Lima",
    "Isabela Ferreira", "Lucas Rocha", "Eduardo Almeida", "Sandra Santos", "Felipe Almeida",
    "Juliana Ferreira", "Diego Gomes", "Luiz Miguel", "Michele Lima", "Ana Beatriz",
    "Cristina Almeida", "Jéssica Andrade", "Luís Felipe", "Gabriel Almeida", "Rogério Martins",
    "Eduardo Oliveira", "Fábio Alves", "Aline Ferreira", "Gabriela Pires", "Luciano Santos",
    "Marcia Oliveira", "Tais Andrade", "Rafael Mendes", "Camila Lima", "Anderson Gomes",
    "Priscila Almeida", "Thais Martins", "Gustavo Nascimento", "Matheus Rocha", "Rafaela Lima",
    "Adriano Ferreira", "Paula Almeida", "Thiago Ferreira", "Maria Júlia", "Roberta Silva",
    "Cecília Mendes", "Márcio Lima", "Bianca Santos", "Marceline Almeida", "Leandro Gomes",
    "Carla Oliveira", "Nicoly Ferreira", "Mariana Lima", "Helena Pires", "Lucas Ferreira",
    "Sofia Gomes", "Ricardo Almeida", "Mônica Andrade", "Eduarda Ribeiro", "João Vitor",
    "Francisco Ferreira", "Renata Santos", "Jorge Almeida", "Natália Pires", "Érika Martins",
    "Fernando Almeida", "Marcos Silva", "Bruno Nascimento", "Débora Oliveira", "Mariana Almeida",
    "Filipe Rocha", "Luiza Silva", "Leonardo Ferreira", "Jéssica Lima", "Vitor Almeida",
    "Juliana Nascimento", "Ana Clara", "Robson Lima", "Felipe Pires", "Gabriel Ferreira",
    "Tiago Lima", "Bianca Almeida", "Thiago Nascimento", "Sabrina Silva", "Ricardo Ferreira",
    "Cristiane Santos", "Adriano Santos", "Giovanna Almeida", "Fernando Lima", "Lucas Oliveira",
    "Paulo Henrique", "Tatiane Martins", "Samuel Ferreira", "Vanessa Santos", "Fábio Almeida",
    "Claudia Lima", "Leandro Ferreira", "Cecília Gomes", "Julio Mendes", "Fernando Costa",
    "Ricardo Mendes", "Isabela Silva", "Sofia Nascimento", "Carlos Alberto", "Renata Lima",
    "Ana Clara", "Jorge Santos", "Lucas Andrade", "Lúcia Martins", "Vitor Hugo",
    "Sabrina Almeida", "Flávio Santos", "Gustavo Ribeiro", "Jéssica Nascimento", "Natália Oliveira",
    "Mariana Ferreira", "Ricardo Santos", "Débora Lima", "Helena Nascimento", "Leonardo Alves",
    "Juliano Ferreira", "Adriana Gomes", "Rafael Almeida", "Gabriela Nascimento", "Mateus Santos",
    "Larissa Ferreira", "Eduardo Martins", "Ana Luiza", "Roberta Almeida", "Thiago Silva",
    "Juliana Rocha", "Renato Almeida", "João Pedro", "Vitor Ferreira", "Natália Santos",
    "Adriano Gomes", "Fernanda Almeida", "Márcio Silva", "Tiago Mendes", "Gabriela Ferreira",
    "Fábio Lima", "André Almeida", "Cecília Santos", "Gabriel Gomes", "Fernando Oliveira",
    "Pedro Lucas", "Ana Beatriz", "Felipe Ferreira", "Isabella Lima", "Samantha Santos",
    "Giovanni Almeida", "Roberta Nascimento", "Ricardo Rocha", "Eduardo Ferreira", "Aline Santos",
    "Mariana Almeida", "Rafael Ribeiro", "Sofia Nascimento", "Leonardo Gomes", "Bianca Lima",
    "Luana Ferreira", "Rogério Santos", "Débora Almeida", "Gabriela Rocha", "Thiago Silva",
    "Jéssica Nascimento", "Cinthia Ferreira", "Paulo Almeida", "Felipe Lima", "Lucas Santos",
    "Juliano Ferreira", "Ana Clara", "Renato Almeida", "Natália Gomes", "Carla Oliveira",
    "Eduarda Ferreira", "Fábio Santos", "Ricardo Almeida", "Patrícia Lima", "Thiago Nascimento",
    "Marcelo Oliveira", "Fernanda Santos", "Juliana Ferreira", "Tatiane Almeida", "Mateus Lima",
    "Robson Ferreira", "Gabriel Martins", "Larissa Silva", "Marceline Santos", "Fernando Almeida",
    "Thiago Lima", "Jéssica Rocha", "André Silva", "Gustavo Ferreira", "Sofia Almeida",
    "Michele Santos", "Rafael Lima", "Eliane Ferreira", "João Paulo", "Marina Almeida",
    "Rogério Nascimento", "Bruno Rocha", "Lucas Alves", "Ana Luiza", "Juliana Santos",
    "Fábio Ferreira", "Thiago Almeida", "Fernanda Lima", "Guilherme Santos", "Marina Ribeiro",
    "Patrícia Ferreira", "Eduardo Santos", "Natália Almeida", "Robson Lima", "Diego Rocha",
    "Gabriela Santos", "Jorge Almeida", "Ricardo Ferreira", "Cecília Lima", "Fernanda Almeida",
    "Tatiane Santos", "Leonardo Ferreira", "Marcos Lima", "Gustavo Almeida", "Priscila Rocha",
    "Tiago Nascimento", "Eduardo Gomes", "Mariana Santos", "Lucas Ribeiro", "Jéssica Almeida",
    "Carlos Lima", "Ana Clara", "Fernando Ferreira", "Guilherme Almeida", "Bruno Santos",
    "Roberta Lima", "Adriana Ferreira", "Juliano Santos", "Natália Almeida", "Vitor Ribeiro",
    "Simone Ferreira", "Gabriela Lima", "Fernando Almeida", "Eduardo Santos", "Marcos Silva",
    "Ana Luiza", "Tatiane Nascimento"]'''


nomes_alunos = [
    ("José Lucas", "M", "Médio"),
    ("Maria Silva", "F", "Médio"),
    ("Carlos Souza", "M", "Fundamental"),
    ("Ana Oliveira", "F", "Médio"),
    ("Lucas Pereira", "M", "Médio"),
    ("Mariana Costa", "F", "Fundamental"),
    ("Fernando Lima", "M", "Médio"),
    ("Tatiane Rocha", "F", "Médio"),
    ("Roberto Almeida", "M", "Médio"),
    ("Juliana Santos", "F", "Médio"),
    ("Gabriel Mendes", "M", "Médio"),
    ("Luciana Gomes", "F", "Fundamental"),
    ("Rafael Ferreira", "M", "Médio"),
    ("Larissa Martins", "F", "Médio"),
    ("Thiago Ribeiro", "M", "Médio"),
    ("Camila Nascimento", "F", "Médio"),
    ("Eduardo Lima", "M", "Fundamental"),
    ("Aline Dias", "F", "Médio"),
    ("Marcelo Pires", "M", "Médio"),
    ("Juliana Alves", "F", "Fundamental"),
    ("Bruno Santos", "M", "Médio"),
    ("Fernanda Vieira", "F", "Fundamental"),
    ("Vinícius Rocha", "M", "Médio"),
    ("Isabella Castro", "F", "Médio"),
    ("João Pedro", "M", "Médio"),
    ("Carolina Martins", "F", "Fundamental"),
    ("Danilo Santos", "M", "Médio"),
    ("Clara Oliveira", "F", "Médio"),
    ("Felipe Mendes", "M", "Fundamental"),
    ("Priscila Ramos", "F", "Médio"),
    ("Tiago Moreira", "M", "Médio"),
    ("Letícia Almeida", "F", "Fundamental"),
    ("Jéssica Costa", "F", "Médio"),
    ("Mateus Ferreira", "M", "Médio"),
    ("Renata Lopes", "F", "Fundamental"),
    ("Gustavo Lima", "M", "Médio"),
    ("Tatiane Silva", "F", "Médio"),
    ("André Souza", "M", "Fundamental"),
    ("Paula Rocha", "F", "Médio"),
    ("Simone Almeida", "F", "Médio"),
    ("Cecília Ferreira", "F", "Fundamental"),
    ("Lucas Alves", "M", "Médio"),
    ("Victor Hugo", "M", "Médio"),
    ("Marina Costa", "F", "Médio"),
    ("Elias Silva", "M", "Fundamental"),
    ("Patrícia Gomes", "F", "Médio"),
    ("Robson Santos", "M", "Médio"),
    ("Amanda Ferreira", "F", "Fundamental"),
    ("Sérgio Almeida", "M", "Médio"),
    ("Denise Martins", "F", "Médio"),
    ("Renan Nascimento", "M", "Fundamental"),
    ("Brenda Lima", "F", "Médio"),
    ("Otávio Oliveira", "M", "Médio"),
    ("Rogério Souza", "M", "Fundamental"),
    ("Marília Castro", "F", "Médio"),
    ("Julio Lima", "M", "Médio"),
    ("Mariane Gomes", "F", "Fundamental"),
    ("Adriana Pires", "F", "Médio"),
    ("Marcelo Silva", "M", "Médio"),
    ("Claudia Almeida", "F", "Fundamental"),
    ("Pedro Henrique", "M", "Médio"),
    ("Sofia Martins", "F", "Médio"),
    ("Diego Santos", "M", "Médio"),
    ("Giselle Ribeiro", "F", "Médio"),
    ("Simone Alves", "F", "Fundamental"),
    ("Eduardo Lopes", "M", "Médio"),
    ("Jessica Ferreira", "F", "Médio"),
    ("Rafael Gomes", "M", "Fundamental"),
    ("Lucas Costa", "M", "Médio"),
    ("Mônica Santos", "F", "Médio"),
    ("Cynthia Oliveira", "F", "Fundamental"),
    ("Gustavo Almeida", "M", "Médio"),
    ("Natália Ferreira", "F", "Médio"),
    ("Luiz Carlos", "M", "Médio"),
    ("Tânia Ribeiro", "F", "Médio"),
    ("Fábio Lima", "M", "Fundamental"),
    ("Luiza Nascimento", "F", "Médio"),
    ("Carlos Alberto", "M", "Médio"),
    ("Débora Alves", "F", "Médio"),
    ("Claudio Ferreira", "M", "Médio"),
    ("Rosana Costa", "F", "Fundamental"),
    ("Flávio Gomes", "M", "Médio"),
    ("Sonia Martins", "F", "Fundamental"),
    ("Júlio César", "M", "Médio"),
    ("Fernanda Pires", "F", "Médio"),
    ("Matheus Silva", "M", "Fundamental"),
    ("Tatiane Ferreira", "F", "Médio"),
    ("Aline Oliveira", "F", "Médio"),
    ("Ricardo Mendes", "M", "Médio"),
    ("Lucas Andrade", "M", "Médio"),
    ("Tatiane Almeida", "F", "Fundamental"),
    ("Felipe Lima", "M", "Médio"),
    ("Bruno Alves", "M", "Médio"),
    ("Eduarda Gomes", "F", "Fundamental"),
    ("Daniel Ferreira", "M", "Médio"),
    ("Rafael Alves", "M", "Médio"),
    ("Fernando Costa", "M", "Fundamental"),
    ("Ruth Oliveira", "F", "Médio"),
    ("Lucas Pereira", "M", "Médio"),
    ("Samantha Rocha", "F", "Médio"),
    ("Guilherme Martins", "M", "Médio"),
    ("Larissa Andrade", "F", "Fundamental"),
    ("Vitor Hugo", "M", "Médio"),
    ("Yasmin Costa", "F", "Fundamental"),
    ("Thiago Pires", "M", "Médio"),
    ("Natália Ramos", "F", "Médio"),
    ("Rafael Costa", "M", "Médio"),
    ("Igor Almeida", "M", "Fundamental"),
    ("Sabrina Gomes", "F", "Médio"),
    ("Luiz Fernando", "M", "Médio"),
    ("Adriana Costa", "F", "Médio"),
    ("Felipe Souza", "M", "Fundamental"),
    ("Gabriela Lima", "F", "Médio"),
    ("Eliane Ferreira", "F", "Médio"),
    ("Samuel Martins", "M", "Médio"),
    ("Juliana Oliveira", "F", "Médio"),
    ("Vinícius Lima", "M", "Fundamental"),
    ("Lúcia Almeida", "F", "Médio"),
    ("Filipe Santos", "M", "Médio"),
    ("Amanda Silva", "F", "Médio"),
    ("Gabriel Ferreira", "M", "Médio"),
    ("Gabriel Gomes", "M", "Médio"),
    ("Camila Oliveira", "F", "Médio"),
    ("Daniela Rocha", "F", "Médio"),
    ("Rafael Nascimento", "M", "Médio"),
    ("Tais Lima", "F", "Fundamental"),
    ("Fernando Ribeiro", "M", "Médio"),
    ("Leonardo Gomes", "M", "Médio"),
    ("Patrícia Santos", "F", "Fundamental"),
    ("Robson Ferreira", "M", "Médio"),
    ("Heloísa Lima", "F", "Médio"),
    ("Marcos Andrade", "M", "Médio"),
    ("Cinthia Almeida", "F", "Fundamental"),
    ("Érica Rocha", "F", "Médio"),
    ("Mariana Nascimento", "F", "Médio"),
    ("Alexandre Lima", "M", "Fundamental"),
    ("Isabela Ferreira", "F", "Médio"),
    ("Lucas Rocha", "M", "Médio"),
    ("Eduardo Almeida", "M", "Fundamental"),
    ("Sandra Santos", "F", "Médio"),
    ("Felipe Almeida", "M", "Médio"),
    ("Juliana Ferreira", "F", "Médio"),
    ("Diego Gomes", "M", "Fundamental"),
    ("Luiz Miguel", "M", "Médio"),
    ("Michele Lima", "F", "Médio"),
    ("Ana Beatriz", "F", "Médio"),
    ("Cristina Almeida", "F", "Fundamental"),
    ("Jéssica Andrade", "F", "Médio"),
    ("Luís Felipe", "M", "Médio"),
    ("Gabriel Almeida", "M", "Médio"),
    ("Rogério Martins", "M", "Médio"),
    ("Eduardo Oliveira", "M", "Fundamental"),
    ("Fábio Alves", "M", "Médio"),
    ("Aline Ferreira", "F", "Médio"),
    ("Gabriela Pires", "F", "Fundamental"),
    ("Luciano Santos", "M", "Médio"),
    ("Marcia Oliveira", "F", "Médio"),
    ("Tais Andrade", "F", "Fundamental"),
    ("Rafael Mendes", "M", "Médio"),
    ("Camila Lima", "F", "Médio"),
    ("Anderson Gomes", "M", "Médio"),
    ("Priscila Almeida", "F", "Fundamental"),
    ("Thais Martins", "F", "Médio"),
    ("Gustavo Nascimento", "M", "Médio"),
    ("Matheus Rocha", "M", "Fundamental"),
    ("Rafaela Lima", "F", "Médio"),
    ("Adriano Ferreira", "M", "Médio"),
    ("Paula Almeida", "F", "Médio"),
    ("Thiago Ferreira", "M", "Fundamental"),
    ("Maria Júlia", "F", "Médio"),
    ("Roberta Silva", "F", "Médio"),
    ("Cecília Mendes", "F", "Médio"),
    ("Márcio Lima", "M", "Fundamental"),
    ("Bianca Santos", "F", "Médio"),
    ("Marceline Almeida", "F", "Médio"),
    ("Leandro Gomes", "M", "Fundamental"),
    ("Carla Oliveira", "F", "Médio"),
    ("Nicoly Ferreira", "F", "Médio"),
    ("Mariana Lima", "F", "Médio"),
    ("Helena Pires", "F", "Médio"),
    ("Lucas Ferreira", "M", "Fundamental"),
    ("Sofia Gomes", "F", "Médio"),
    ("Ricardo Almeida", "M", "Médio"),
    ("Mônica Andrade", "F", "Fundamental"),
    ("Eduarda Ribeiro", "F", "Médio"),
    ("João Vitor", "M", "Médio"),
    ("Francisco Ferreira", "M", "Médio"),
    ("Renata Santos", "F", "Fundamental"),
    ("Jorge Almeida", "M", "Médio"),
    ("Natália Pires", "F", "Médio"),
    ("Érika Martins", "F", "Médio"),
    ("Fernando Almeida", "M", "Fundamental"),
    ("Marcos Silva", "M", "Médio"),
    ("Bruno Nascimento", "M", "Médio"),
    ("Débora Oliveira", "F", "Médio"),
    ("Mariana Almeida", "F", "Médio"),
    ("Filipe Rocha", "M", "Fundamental"),
    ("Luiza Silva", "F", "Médio"),
    ("Leonardo Ferreira", "M", "Médio"),
    ("Jéssica Lima", "F", "Médio"),
    ("Vitor Almeida", "M", "Fundamental"),
    ("Juliana Nascimento", "F", "Médio"),
    ("Ana Clara", "F", "Médio"),
    ("Robson Lima", "M", "Médio"),
    ("Felipe Pires", "M", "Fundamental"),
    ("Gabriel Ferreira", "M", "Médio"),
    ("Tiago Lima", "M", "Médio"),
    ("Bianca Almeida", "F", "Médio"),
    ("Thiago Nascimento", "M", "Fundamental"),
    ("Sabrina Silva", "F", "Médio"),
    ("Ricardo Ferreira", "M", "Médio"),
    ("Cristiane Santos", "F", "Fundamental"),
    ("Adriano Santos", "M", "Médio"),
    ("Giovanna Almeida", "F", "Médio"),
    ("Fernando Lima", "M", "Médio"),
    ("Lucas Oliveira", "M", "Fundamental"),
    ("Paulo Henrique", "M", "Médio"),
    ("Tatiane Martins", "F", "Médio"),
    ("Samuel Ferreira", "M", "Médio"),
    ("Vanessa Santos", "F", "Fundamental"),
    ("Fábio Almeida", "M", "Médio"),
    ("Claudia Lima", "F", "Médio"),
    ("Leandro Ferreira", "M", "Fundamental"),
    ("Cecília Gomes", "F", "Médio"),
    ("Julio Mendes", "M", "Médio"),
    ("Fernando Costa", "M", "Médio"),
    ("Ricardo Mendes", "M", "Fundamental"),
    ("Isabela Silva", "F", "Médio"),
    ("Sofia Nascimento", "F", "Médio"),
    ("Carlos Alberto", "M", "Médio"),
    ("Renata Lima", "F", "Fundamental"),
    ("Ana Clara", "F", "Médio"),
    ("Jorge Santos", "M", "Médio"),
    ("Lucas Andrade", "M", "Médio"),
    ("Lúcia Martins", "F", "Fundamental"),
    ("Vitor Hugo", "M", "Médio"),
    ("Sabrina Almeida", "F", "Médio"),
    ("Flávio Santos", "M", "Médio"),
    ("Gustavo Ribeiro", "M", "Fundamental"),
    ("Jéssica Nascimento", "F", "Médio"),
    ("Natália Oliveira", "F", "Médio"),
    ("Mariana Ferreira", "F", "Médio"),
    ("Ricardo Santos", "M", "Fundamental"),
    ("Débora Lima", "F", "Médio"),
    ("Helena Nascimento", "F", "Médio"),
    ("Leonardo Alves", "M", "Fundamental"),
    ("Juliano Ferreira", "M", "Médio"),
    ("Adriana Gomes", "F", "Médio"),
    ("Rafael Almeida", "M", "Médio"),
    ("Gabriela Nascimento", "F", "Médio"),
    ("Mateus Santos", "M", "Fundamental"),
    ("Larissa Ferreira", "F", "Médio"),
    ("Eduardo Martins", "M", "Médio"),
    ("Ana Luiza", "F", "Médio"),
    ("Roberta Almeida", "F", "Fundamental"),
    ("Thiago Silva", "M", "Médio"),
    ("Juliana Rocha", "F", "Médio"),
    ("Renato Almeida", "M", "Médio"),
    ("João Pedro", "M", "Fundamental"),
    ("Vitor Ferreira", "M", "Médio"),
    ("Natália Santos", "F", "Médio"),
    ("Adriano Gomes", "M", "Médio"),
    ("Fernanda Almeida", "F", "Fundamental"),
    ("Cristina Almeida", "F", "Médio"),
    ("Jéssica Andrade", "F", "Médio"),
    ("Luís Felipe", "M", "Fundamental"),
    ("Gabriel Almeida", "M", "Médio"),
    ("Rogério Martins", "M", "Médio"),
    ("Eduardo Oliveira", "M", "Médio"),
    ("Fábio Alves", "M", "Fundamental"),
    ("Aline Ferreira", "F", "Médio"),
    ("Gabriela Pires", "F", "Médio"),
    ("Luciano Santos", "M", "Médio"),
    ("Márcia Oliveira", "F", "Fundamental"),
    ("Tais Andrade", "F", "Médio"),
    ("Rafael Mendes", "M", "Médio"),
    ("Camila Lima", "F", "Fundamental"),
    ("Anderson Gomes", "M", "Médio"),
    ("Priscila Almeida", "F", "Médio"),
    ("Thais Martins", "F", "Médio"),
    ("Gustavo Nascimento", "M", "Fundamental"),
    ("Matheus Rocha", "M", "Médio"),
    ("Rafaela Lima", "F", "Médio"),
    ("Adriano Ferreira", "M", "Fundamental"),
    ("Paula Almeida", "F", "Médio"),
    ("Thiago Ferreira", "M", "Médio"),
    ("Maria Júlia", "F", "Médio"),
    ("Roberta Silva", "F", "Fundamental"),
    ("Cecília Mendes", "F", "Médio"),
    ("Márcio Lima", "M", "Médio"),
    ("Bianca Santos", "F", "Médio"),
    ("Marceline Almeida", "F", "Fundamental"),
    ("Leandro Gomes", "M", "Médio"),
    ("Carla Oliveira", "F", "Médio"),
    ("Nicoly Ferreira", "F", "Médio"),
    ("Mariana Lima", "F", "Fundamental"),
    ("Helena Pires", "F", "Médio"),
    ("Lucas Ferreira", "M", "Médio"),
    ("Sofia Gomes", "F", "Médio"),
    ("Ricardo Almeida", "M", "Fundamental"),
    ("Mônica Andrade", "F", "Médio"),
    ("Eduarda Ribeiro", "F", "Médio"),
    ("João Vitor", "M", "Fundamental"),
    ("Francisco Ferreira", "M", "Médio"),
    ("Renata Santos", "F", "Médio"),
    ("Jorge Almeida", "M", "Médio"),
    ("Natália Pires", "F", "Fundamental"),
    ("Érika Martins", "F", "Médio"),
    ("Fernando Almeida", "M", "Médio"),
    ("Marcos Silva", "M", "Médio"),
    ("Bruno Nascimento", "M", "Fundamental"),
    ("Débora Oliveira", "F", "Médio"),
    ("Mariana Almeida", "F", "Médio"),
    ("Filipe Rocha", "M", "Médio"),
    ("Luiza Silva", "F", "Fundamental"),
    ("Leonardo Ferreira", "M", "Médio"),
    ("Jéssica Lima", "F", "Médio"),
    ("Vitor Almeida", "M", "Médio"),
    ("Juliana Nascimento", "F", "Fundamental"),
    ("Ana Clara", "F", "Médio"),
    ("Robson Lima", "M", "Médio"),
    ("Felipe Pires", "M", "Médio"),
    ("Gabriel Ferreira", "M", "Fundamental"),
    ("Tiago Lima", "M", "Médio"),
    ("Bianca Almeida", "F", "Médio"),
    ("Thiago Nascimento", "M", "Médio"),
    ("Sabrina Silva", "F", "Fundamental"),
    ("Ricardo Ferreira", "M", "Médio"),
    ("Cristiane Santos", "F", "Médio"),
    ("Adriano Santos", "M", "Médio"),
    ("Giovanna Almeida", "F", "Fundamental"),
    ("Fernando Lima", "M", "Médio"),
    ("Lucas Oliveira", "M", "Médio"),
    ("Paulo Henrique", "M", "Médio"),
    ("Tatiane Martins", "F", "Fundamental"),
    ("Samuel Ferreira", "M", "Médio"),
    ("Vanessa Santos", "F", "Médio"),
    ("Fábio Almeida", "M", "Fundamental"),
    ("Claudia Lima", "F", "Médio"),
    ("Leandro Ferreira", "M", "Médio"),
    ("Cecília Gomes", "F", "Médio"),
    ("Julio Mendes", "M", "Fundamental"),
    ("Fernando Costa", "M", "Médio"),
    ("Ricardo Mendes", "M", "Médio"),
    ("Isabela Silva", "F", "Médio"),
    ("Sofia Nascimento", "F", "Fundamental"),
    ("Carlos Alberto", "M", "Médio"),
    ("Renata Lima", "F", "Médio"),
    ("Ana Clara", "F", "Médio"),
    ("Jorge Santos", "M", "Médio"),
    ("Lucas Andrade", "M", "Fundamental"),
    ("Lúcia Martins", "F", "Médio"),
    ("Vitor Hugo", "M", "Médio"),
    ("Sabrina Almeida", "F", "Médio"),
    ("Flávio Santos", "M", "Fundamental"),
    ("Gustavo Ribeiro", "M", "Médio"),
    ("Jéssica Nascimento", "F", "Médio"),
    ("Natália Oliveira", "F", "Médio"),
    ("Mariana Ferreira", "F", "Fundamental"),
    ("Ricardo Santos", "M", "Médio"),
    ("Débora Lima", "F", "Médio"),
    ("Helena Nascimento", "F", "Médio"),
    ("Leonardo Alves", "M", "Fundamental")
]